version: "3.8"
services:
  docker-apache:
    image: my-php-site:latest
    container_name: docker-apache
    ports:
      - "80:80"
    depends_on:
      - mysql-db  

  mysql-db:
    image: mysql:5.6
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: inventory
      # MYSQL_USER: db_user
      # MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db/inventory.sql:/docker-entrypoint-initdb.d/inventory.sql:ro